#pragma once

#include "ruleTemplates/autoindexRule.hpp"
#include "ruleTemplates/cgiExtensionRule.hpp"
#include "ruleTemplates/cgiRule.hpp"
#include "ruleTemplates/cgiTimeoutRule.hpp"
#include "ruleTemplates/defineRule.hpp"
#include "ruleTemplates/errorpageRule.hpp"
#include "ruleTemplates/includeRule.hpp"
#include "ruleTemplates/indexRule.hpp"
#include "ruleTemplates/maxBodySizeRule.hpp"
#include "ruleTemplates/methodsRule.hpp"
#include "ruleTemplates/portRule.hpp"
#include "ruleTemplates/returnRule.hpp"
#include "ruleTemplates/rootRule.hpp"
#include "ruleTemplates/servernameRule.hpp"
#include "ruleTemplates/uploadstoreRule.hpp"

#include "ruleTemplates/locationRule.hpp"
#include "ruleTemplates/serverconfigRule.hpp"